[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install -g npm@latest", "npm ci"]

[phases.build]
cmds = ["npm run build", "npm install -g serve"]

[start]
cmd = "serve dist -l $PORT"
